WSTProject/recipe/urls.py
#urls.py
from django.urls import path
from . import views

app_name = 'recipe'
urlpatterns = [
    #MAIN PAGE
    path('', views.view_recipes, name='view_recipes'),
    #MY RECIPE PAGE
    path('me/', views.view_user_recipes, name='view_user_recipes'),
    #RECIPE DETAILS
    path('detail/<int:recipe_primary_key>', views.view_recipe_detail, name='view_recipe_detail'),
    #RECIPE FORM
    path('create/', views.create_recipe, name="create_recipe"),
    #ETO NEED MONG AYUSIN NEIL!!!
    path('update/<int:recipe_primary_key>/', views.update_recipe, name="update_recipe"),
    path('delete/<int:recipe_primary_key>/', views.delete_recipe, name ="delete_recipe"),
    #INGREDIENT FORM
    path('<int:recipe_primary_key>/ingredient/create/', views.create_ingredient, name='create_ingredient'),
    path('<int:recipe_primary_key>/ingredient/update/<int:ingredient_primary_key>/', views.update_ingredient, name='update_ingredient'),
    path('<int:recipe_primary_key>/ingredient/delete/<int:ingredient_primary_key>/', views.delete_ingredient, name='delete_ingredient'),
    #INSTRUCTION FORM
    path('<int:recipe_primary_key>/instruction/create/', views.create_instruction, name='create_instruction'),
    path('<int:recipe_primary_key>/instruction/update/<int:instruction_primary_key>/', views.update_instruction, name='update_instruction'),
    path('<int:recipe_primary_key>/instruction/delete/<int:instruction_primary_key>/', views.delete_instruction, name='delete_instruction'),
    #STATISTICS PAGE
    path('category-stats/', views.recipe_category_stats, name='category_stats'),
    path('category-data/', views.get_category_data, name='category_data'),
    path('user-data/', views.get_user_data, name='user_data'),
]

WSTProject/user_profile/urls.py
from django.urls import path
from . import views

app_name = "profile"
urlpatterns = [
    path('', views.view_profile, name='view_profile'),
    path('update/', views.update_profile, name='update_profile'),
    path('password/update/', views.update_password, name='update_password'),
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.home, name = "home"),
    path('signin/', views.signin, name ="signin"),
    path('signup/', views.signup, name ="signup"),
    path('signout/', views.signout, name ="signout"),
]

main/models.py
from django.db import models

# Create your models here.

WSTProject/main/views.py
from django.contrib.auth.models import User, auth
from django.shortcuts import render, redirect
from django.contrib import messages

from user_profile.models import Profile

def home(request):
    if request.user.is_authenticated:
        # If user is logged in, redirect to recipes page
        return redirect('recipe:view_recipes')
    else:
        # If user is not logged in, show the home page
        return render(request, 'main/home.html', {
            'title': 'Home'
        })

def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            # A backend authenticated the credentials.
            auth.login(request, user)
            messages.success(request, 'Login Successful. Welcome back!')
            print('Login Successful. Welcome back!')
            return redirect('recipe:view_recipes')
        else:
            # No backend authenticated the credentials.
            messages.error(request, 'User does not exist. Please check your username and password!')
            print('User does not exist. Please check your password and username!')
            return redirect('main:signin')

    return render(request, 'main/signin.html', {
        'title': "Signin"
    })

def signup(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            if User.objects.filter(email=email).exists():
                messages.warning(request, 'The Email already exist')
                print("The Email already exist")
                return redirect('main:signup')
            elif User.objects.filter(username=username).exists():
                messages.warning(request, 'The Username already taken')
                print("The Username already taken")
                return redirect('main:signup')
            else:
                #Create the user
                new_user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)
                new_user.save()
                #Log the user using credentials.
                user_credentials = auth.authenticate(username=username, password=password)
                auth.login(request, user_credentials)
                #Create a Profile for the new user
                get_new_user = User.objects.get(username=username)
                new_profile = Profile.objects.create(user=get_new_user)
                new_profile.save()
                #Redirect the user.
                messages.success(request, 'Account created successfully. Welcome to Community!')
                print("Account created successfully. Welcome to Community!")
                return redirect('recipe:view_recipes')
        else:
            messages.error(request, "The password don't match.")
            print("The password don't match")
            return redirect('main:signup')
    return render(request, 'main/signup.html', {
        'title': "Signup"
    })

def signout(request):
    auth.logout(request)
    messages.success(request, 'Logout Successful. Have a nice day!')
    print("Logout Successful. Have a nice day!")
    return redirect('main:signin')

main/views.py
from django.contrib.auth.models import User, auth
from django.shortcuts import render, redirect
from django.contrib import messages

from user_profile.models import Profile

def home(request):
    if request.user.is_authenticated:
        # If user is logged in, redirect to recipes page
        return redirect('recipe:view_recipes')
    else:
        # If user is not logged in, show the home page
        return render(request, 'main/home.html', {
            'title': 'Home'
        })

def signin(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        
        if user is not None:
            # A backend authenticated the credentials.
            auth.login(request, user)
            messages.success(request, 'Login Successful. Welcome back!')
            print('Login Successful. Welcome back!')
            return redirect('recipe:view_recipes')
        else:
            # No backend authenticated the credentials.
            messages.error(request, 'User does not exist. Please check your username and password!')
            print('User does not exist. Please check your password and username!')
            return redirect('recipe:signin')

    return render(request, 'main/signin.html', {
        'title': "Signin"
    })

def signup(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password == confirm_password:
            if User.objects.filter(email=email).exists():
                messages.warning(request, 'The Email already exist')
                print("The Email already exist")
                return redirect('main:signup')
            elif User.objects.filter(username=username).exists():
                messages.warning(request, 'The Username already taken')
                print("The Username already taken")
                return redirect('main:signup')
            else: 
                #Create the user
                new_user = User.objects.create_user(first_name=first_name, last_name=last_name, username=username, email=email, password=password)
                new_user.save()
                #Log the user using credentials.
                user_credentials = auth.authenticate(username=username, password=password)
                auth.login(request, user_credentials)
                #Create a Profile for the new user
                get_new_user = User.objects.get(username=username)
                new_profile = Profile.objects.create(user=get_new_user)
                new_profile.save()
                #Redirect the user.
                messages.success(request, 'Account created successfully. Welcome to Community!')
                print("Account created successfully. Welcome to Community!")
                return redirect('recipe:view_recipes')
        else:
            messages.error(request, "The password don't match.")
            print("The password don't match")
            return redirect('main:signup')
    return render(request, 'main/signup.html', {
        'title': "Signup"
    })

def signout(request):
    auth.logout(request)
    messages.success(request, 'Logout Successful. Have a nice day!')
    print("Logout Successful. Have a nice day!")
    return redirect('main:signin')

WSTProject/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <title>{% block title %}{% endblock %} | FoodDictionary</title>
</head>
<body>
    {% if request.user.is_authenticated %}
      <nav class="border-gray-200 bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="{% url 'recipe:view_recipes' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="{% static 'logo.svg' %}" class="h-10" alt="wstIcon Logo" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Lasa Lokal</span>
        </a>
        <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
            <button type="button" class="flex text-sm bg-gray-800 rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
              <span class="sr-only">Open user menu</span>
              <img class="w-8 h-8 rounded-full" src="{{ request.user.profile.image.url }}" alt="{{ request.user.first_name }} {{ request.user.last_name }} photo">
            </button>
            <!-- Dropdown menu -->
            <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
              <div class="px-4 py-3">
                <span class="block text-sm text-gray-900 dark:text-white">{{ request.user.first_name }} {{ request.user.last_name }}</span>
                <span class="block text-sm  text-gray-500 truncate dark:text-gray-400">{{ request.user.email }}</span>
              </div>
              <ul class="py-2" aria-labelledby="user-menu-button">
                <li>
                  <a href="{% url 'profile:view_profile' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Profile</a>
                </li>
                <li>
                  <a href="{% url 'main:signout' %}" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Sign out</a>
                </li>
              </ul>
            </div>
            <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-user" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
              </svg>
          </button>
        </div>
        <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
          <ul class="flex flex-col font-medium mt-4 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-transparent dark:bg-gray-800 md:dark:bg-transparent dark:border-gray-700">
            <li>
              <a href="{% url 'recipe:view_recipes' %}" class="block py-2 px-3 md:p-0 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:dark:text-blue-500 dark:bg-blue-600 md:dark:bg-transparent" aria-current="page">Home</a>
            </li>
            <li>
              <a href="{% url 'recipe:view_user_recipes' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Dashboard</a>
            </li>
            <li>
              <a href="{% url 'recipe:create_recipe' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Create Recipe</a>
            </li>
            <li>
              <a href="{% url 'recipe:category_stats' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Statistics</a>
            </li>
          </ul>
        </div>
        </div>
      </nav>
      <div class="w-full border-b border-gray-200 dark:border-gray-700"></div>
    {% else %}
    <nav class="border-gray-200 bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
        <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
          <a href="{% url 'main:home' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
              <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
              <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Lasa Lokal</span>
          </a>
          <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
              <span class="sr-only">Open main menu</span>
              <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
              </svg>
          </button>
          <div class="hidden w-full md:block md:w-auto" id="navbar-default">
            <ul class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 rtl:space-x-reverse md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
              <li>
                <a href="{% url 'main:signin' %}" class="block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500" aria-current="page">Login</a>
              </li>
              <li>
                <a href="{% url 'main:signup' %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent">Register</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="w-full border-b border-gray-200 dark:border-gray-700"></div>
      {% endif %}
      <div class = "max-w-screen-xl mx-auto md:px-3 bg-white dark:bg-gray-900">
        {% for message in messages %}
            {% if "success" in message.tags %}
                <div id="alert-3" class="flex items-center p-4 mb-4 text-green-800 rounded-lg bg-green-50 dark:bg-gray-800 dark:text-green-400" role="alert">
                  <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                  </svg>
                  <span class="sr-only">Info</span>
                  <div class="ms-3 text-sm font-medium">
                    {{ message }}
                  </div>
                  <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-green-50 text-green-500 rounded-lg focus:ring-2 focus:ring-green-400 p-1.5 hover:bg-green-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-green-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-3" aria-label="Close">
                    <span class="sr-only">Close</span>
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                  </button>
                </div>
            {% elif "warning" in message.tags %}
              <div id="alert-4" class="flex items-center p-4 mb-4 text-yellow-800 rounded-lg bg-yellow-50 dark:bg-gray-800 dark:text-yellow-300" role="alert">
                <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                </svg>
                <span class="sr-only">Info</span>
                <div class="ms-3 text-sm font-medium">
                  {{ message }}
                </div>
                <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-yellow-50 text-yellow-500 rounded-lg focus:ring-2 focus:ring-yellow-400 p-1.5 hover:bg-yellow-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-yellow-300 dark:hover:bg-gray-700" data-dismiss-target="#alert-4" aria-label="Close">
                  <span class="sr-only">Close</span>
                  <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                  </svg>
                </button>
              </div>
            {% elif "error" in message.tags %}
              <div id="alert-2" class="flex items-center p-4 mb-4 text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
                <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                </svg>
                <span class="sr-only">Info</span>
                <div class="ms-3 text-sm font-medium">
                  {{ message }}
                </div>
                <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-red-50 text-red-500 rounded-lg focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-red-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-2" aria-label="Close">
                  <span class="sr-only">Close</span>
                  <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                  </svg>
                </button>
              </div>
            {% else %}
              <div id="alert-1" class="flex items-center p-4 mb-4 text-blue-800 rounded-lg bg-blue-50 dark:bg-gray-800 dark:text-blue-400" role="alert">
                <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                  <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
                </svg>
                <span class="sr-only">Info</span>
                <div class="ms-3 text-sm font-medium">
                  {{ message }}
                </div>
                  <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-blue-50 text-blue-500 rounded-lg focus:ring-2 focus:ring-blue-400 p-1.5 hover:bg-blue-200 inline-flex items-center justify-center h-8 w-8 dark:bg-gray-800 dark:text-blue-400 dark:hover:bg-gray-700" data-dismiss-target="#alert-1" aria-label="Close">
                    <span class="sr-only">Close</span>
                    <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                    </svg>
                </button>
              </div>
            {% endif %}
        {% endfor %}
      </div>
      {% block content %}
      {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>

</body>
</html>